### ISSUE TITLE
gogoanime

### ISSUE THREAD

**Issue by danielhyuuga** [cywteow/cywteow.github.io#1]
gogoanime link is dead

**Comment by cywteow** [comment]
Thanks for reporting.

I fixed vidstreaming and Gogo server. Only 2 server working atm. 

If your gogoanime doesn't update to v1.3.3 automatically, go to "add ons/add-on browser" -> "Install from repository" -> Hold press on "cywteow Add-ons" -> select "check for updates". You should see gogoanime updated to 1.3.3 from there.

Hope it helps.

**Comment by cywteow** [comment]
How long have it been down?

**Comment by danielhyuuga** [comment]
For quite a while now. Still not fixed because the addon is using host .video domain. Need to update to .app

**Comment by cywteow** [comment]
Not fixed? It seems to be working for me now. Gogoanime has multiple proxy server like gogoanime.pro gogoanime.vc

**Comment by danielhyuuga** [comment]
Oh just realised domain is blocked by dns. Will work on workaround soon.
